export enum EPaginationHeaders {
  PAGE_LIMIT = 'X-PAGE-LIMIT',
  PAGE_OFFSET = 'X-PAGE-OFFSET',
  CURRENT_PAGE = 'X-CURRENT-PAGE',
  TOTAL_PAGES = 'X-TOTAL-PAGES',
  TOTAL_RECORDS = 'X-TOTAL-RECORDS'
}
